raredepot/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

raredepot/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.popular_list, name='popular_list'),
    path('shop/', views.product_list, name='product_list'),
    path('shop/<slug:slug>/', views.product_detail,
         name='product_detail'),
    path('shop/category/<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
]

raredepot/raredepot/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('users.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('orders/', include('payment.urls', namespace='payment')),
    path('', include('main.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

raredepot/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

raredepot/main/models.py
from email.mime import image
from enum import auto
from tabnanny import verbose
from unicodedata import category
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=20,
                            unique=True)
    slug = models.SlugField(max_length=20,
                            unique=True)
    

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse("main:product_list_by_category",
                       args=[self.slug])
    


    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(default=0.00, max_digits=4,
                                   decimal_places=2)
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
        

    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse('main:product_detail',
                       args=[self.slug])
    

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price
    

class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images',
                                on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    
    
    def __str__(self):
        return f'{self.product.name} - {self.image.name}'

raredepot/main/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Product, Category
from cart.forms import CartAddProductForm

def popular_list(request):
    products = Product.objects.filter(available=True)[:3]
    return render(request,
                  'main/index/index.html',
                  {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product,
                                slug=slug,)
                                #available=True)
    cart_product_form = CartAddProductForm()                            
    return render(request,
                  'main/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


def product_list(request, category_slug=None):
    page = request.GET.get('page', 1)
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    paginator = Paginator(products, 10)
    current_page = paginator.page(int(page))
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        paginator = Paginator(products.filter(category=category), 10)
        current_page = paginator.page(int(page))
    return render(request,
                  'main/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': current_page,
                   'slug_url': category_slug})

raredepot/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    {% comment %} bootstrap {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap\css\bootstrap.min.css' %}">
    {% comment %} css {% endcomment %}
    <link rel="stylesheet" href="{% static "css/base.css" %}">
</head>
<body>
    <header class="header sticky-top">
        <div class="header-container d-flex">
            <navbar class="header-nav pt-4">
                <ul class="header-list d-flex">
                    <li>
                        <a href="/" class="nav-a m-3">Home</a>
                    </li>
                    <li>
                        <a href="/shop" class="nav-a m-3">Shop</a>
                    </li>
                </ul>
            </navbar>
            <div class="header-logo">
                <a href="/shop"><img src="{% static "img/raredepotlogo.png" %}" alt="" class="raredepot-logo"></a>
            </div>
            <div class="header-profile pt-2">
                <a href="{% url 'cart:cart_detail' %}"><img src="{% static "img/grob.png" %}" class="grob" alt=""></a>
                {% if user.is_authenticated %}
                    <a href="{% url "users:profile" %}">PROFILE</a>
                {% else %}
                <a href="{% url "users:login" %}" class="m-2">LOGIN</a>
                {% endif %}
                <p class="cart-quantity">
                    {% with cart_quantity=cart|length %}
                        {% if cart_quantity > 0 %}
                            {{ cart_quantity }}
                        {% else %}
                            0
                        {% endif %}
                    {% endwith %}
                </p>
            </div>
        </div>
    </header>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
    



    {% comment %} js for bootstrap {% endcomment %}
    <script src="{% static "bootstrap\js\bootstrap.bundle.min.js" %}"></script>
</body>
</html>