raredepot/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

raredepot/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

raredepot/raredepot/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('users.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('orders/', include('payment.urls', namespace='payment')),
    path('', include('main.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

raredepot/orders/models.py
from itertools import product
from pyexpat import model
from django.db import models
from main.models import Product
from users.models import User


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT,
                             blank=True, null=True, default=None)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    created = models.DateField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)


    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]


    def __str__(self):
        return f'Order {self.id}'  
    

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)


    def __str__(self):
        return str(self.id)
    

    def get_cost(self):
        return self.price * self.quantity

raredepot/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'first_name', 'last_name', 'email',
                  'address', 'postal_code', 'city']
        
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        if self.request.user.is_authenticated:
            self.initial['first_name'] = self.request.user.first_name
            self.initial['last_name'] = self.request.user.last_name
            self.initial['email'] = self.request.user.email
    
    
    def save(self, commit=True):
        order = super().save(commit=False)
        order.user = self.request.user
        if commit:
            order.save()
        return order

raredepot/orders/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST, request=request)
        if form.is_valid():
            order = form.save()
            for item in cart:
                discounted_price = item['product'].sell_price()
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=discounted_price,
                                         quantity=item['quantity'])
            cart.clear()
            request.session['order_id'] = order.id
            return redirect(reverse('payment:process'))
    else:
        form = OrderCreateForm(request=request)
    return render(request, 
                  'orders/order/create.html',
                  {'cart': cart,
                   'form': form})

raredepot/orders/templates/order/create.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Create Order{% endblock title %}

{% block content %}
    <div class="forcreate">
        <div class="profile bg-white p-4 mb-4 mx-2">
            <h2 class="mb-2">Create Order</h2>
            <form action="" method="post" class="order-form">
                {% csrf_token %}
                <div class="col-md-12 mb-3">
                    <label for="id_first_name" class="form-label">First Name</label>
                    <input type="text" class="form-control form-styleprofile" id="id_first_name"
                    name="first_name" placeholder="Your First Name" value="{{ form.first_name.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_last_name" class="form-label">Last Name</label>
                    <input type="text" class="form-control form-styleprofile" id="id_last_name"
                    name="last_name" placeholder="Your Last Name" value="{{ form.last_name.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    <input type="text" class="form-control form-styleprofile" id="id_email"
                    name="email" placeholder="Your Email" value="{{ form.email.value|default:'' }}" required>
                </div>

                <div class="col-md-12 mb-3">
                    <label for="id_address" class="form-label">Address</label>
                    <input type="text" class="form-control form-styleprofile" id="id_address"
                    name="address" placeholder="Your Address" value="{{ form.address.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_postal_code" class="form-label">Postal Code</label>
                    <input type="text" class="form-control form-styleprofile" id="id_postal_code"
                    name="postal_code" placeholder="Your Postal Code" value="{{ form.postal_code.value|default:'' }}" required>
                </div>
                <div class="col-md-12 mb-3">
                    <label for="id_city" class="form-label">City</label>
                    <input type="text" class="form-control form-styleprofile" id="id_city"
                    name="city" placeholder="Your City" value="{{ form.city.value|default:'' }}" required>
                </div>
                <p><input type="submit" value="Place Order"></p>
                {% csrf_token %}
            </form>
        </div>
        <div class="checkout">
            <h1>Checkout</h1>
            <div class="order-info">
                {% for item in cart %}
                    <li>
                        {{ item.quantity }}x {{ item.product.name }}
                        <p>$ {{ item.total_price }}</p>
                    </li>
                    <p>Total: $ {{ cart.get_total_price }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

raredepot/orders/templates/order/created.html
{% extends 'main/base.html' %}

{% block title %}Order Created{% endblock title %}

{% block content %}
    <h1 class="text-center mt-5">Your order was created</h1>
{% endblock content %}