raredepot/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

raredepot/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.popular_list, name='popular_list'),
    path('shop/', views.product_list, name='product_list'),
    path('shop/<slug:slug>/', views.product_detail,
         name='product_detail'),
    path('shop/category/<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
]

raredepot/raredepot/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('users.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('orders/', include('payment.urls', namespace='payment')),
    path('', include('main.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

raredepot/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

raredepot/users/models.py
from django.db import models
from django.contrib.auth.models import \
                            AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', blank=True,
                              null=True)
    

    class Meta:
        db_table = 'user'


    def __str__(self):
        return self.username
        

raredepot/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, \
    UserCreationForm, UserChangeForm
from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()
    
    
    class Meta:
        model = User
        fields = ['username', 'password']
        

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )
        
        
        first_name = forms.CharField()
        last_name = forms.CharField()
        username = forms.CharField()
        email = forms.CharField()
        password1 = forms.CharField()
        password2 = forms.CharField()
        

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
        )
    
    
        image = forms.ImageField(required=False)
        first_name = forms.CharField()
        last_name = forms.CharField()
        username = forms.CharField()
        email = forms.CharField()

raredepot/users/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import UserLoginForm, UserRegistrationForm, \
    ProfileForm
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from orders.models import Order, OrderItem


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username,
                                     password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:product_list'))
    else:
        form = UserLoginForm()
    return render(request, 'users/login.html', {'form': form})


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            messages.success(
                request, f'{user.username}, Successful Registration'
            )
            return HttpResponseRedirect(reverse('user:login'))
    else:
        form = UserRegistrationForm()
    return render(request, 'users/registration.html')


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user,
                           files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile was changed')
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
    
    orders = Order.objects.filter(user=request.user).prefetch_related(
        Prefetch(
            'items',
            queryset=OrderItem.objects.select_related('product'),
        )
    ).order_by('-id')
    return render(request, 'users/profile.html',
                  {'form': form,
                   'orders': orders})


def logout(request):
    auth.logout(request)
    return redirect(reverse('main:product_list'))

raredepot/users/templates/users/login.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
    <section class="login d-flex">
        <div class="login-title">
            <h2>Login</h2>
            <form action="{% url "user:login" %}" method="post">
                {% csrf_token %}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <div class="mb-3">
                    <label for="id_username" class="form-label form-style">Username</label>
                    <input type="text" class="form-control form-style"
                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                    name="username" id="id_username" placeholder="Input username" required>
                </div>
                <div class="mb-3">
                    <label for="id_password" class="form-label form-style">Password</label>
                    <input type="password" class="form-control form-style"
                    name="password" id="id_password" placeholder="Your password" required>
                </div>
                <button type="submit" class="login-btn form-style">Login</button>
            </form>
            <div class="reset-pass">
                <hr>
                <div class="mt-3">
                    <a href="#">Reset Password</a> | <a href="{% url "user:registration" %}">Create Account</a>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

raredepot/users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Profile{% endblock title %}

{% block content %}
    <div class="d-flex">
        <div class="windowp d-flex bg-white p-4 mb-4 mx-2 rounded">
            <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                <h2 class="mb-2">Profile</h2>
                {% csrf_token %}
                <div class="d-flex">
                    <div class="1box">
                        <div class="col-md-12 mb-3">
                            {% if user.image %}
                                <img src="{{ user.image.url }}" alt="Avatar" class="img-fluid"
                                style="max-width: 150px; max-height: 150px;">
                            {% else %}
                                <img src="{% static 'img/noimage.jpg' %}" alt="Avatar" class="img-fluid"
                                style="max-width: 150px; max-height: 150px;">
                            {% endif %}
                            <input type="file" class="form-control form-styleprofile mt-2" id="id_image"
                            name="image" accept="image/*">
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_first_name" class="form-label">First Name</label>
                            <input type="text" class="form-control form-styleprofile" id="id_first_name"
                            name="first_name" placeholder="Your First Name" value="{{ form.first_name.value }}"
                            required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_last_name" class="form-label">Last Name</label>
                            <input type="text" class="form-control form-styleprofile" id="id_last_name"
                            name="last_name" placeholder="Your Last Name" value="{{ form.last_name.value }}"
                            required>
                        </div>
                    </div>
                    <div class="box2">
                        <div class="col-md-12 mb-3">
                            <label for="id_username" class="form-label">Username</label>
                            <input type="text" class="form-control form-styleprofile" id="id_username"
                            name="username" placeholder="Your Username" value="{{ form.username.value }}"
                            required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_email" class="form-label">Email</label>
                            <input type="email" class="form-control form-styleprofile" id="id_email"
                            name="email" placeholder="Your Email" value="{{ form.email.value }}"
                            required>
                        </div>
                    </div>
                </div>
                <div class="btns d-flex gap-4 mt-4">
                    <button type="submit" class="profile-btn">Save</button>
                    <a class="profile-btn" href="{% url "user:logout" %}">Logout</a>
                </div>
                
            </form>
            <div class="orders">
                <h2 class="mb-2">Your Orders</h2>   
                {% if orders %}
                    <div class="orderss">
                        {% for order in orders %}
                            <div class="order-cart">
                                <h5 class="order-title">Order № {{ order.id }}</h5>
                                <p class="order-desc">
                                    {% for item in order.items.all %}
                                        <div class="orders-carts">
                                            <span class="dadad">Name: </span><a class="" href="{% url 'main:product_detail' item.product.slug %}">{{ item.product.name }}</a>
                                            <br>
                                            <span class="dadad">Quantity:</span> {{ item.quantity }},
                                            <span class="dadad">Price: $ {{ item.price }}</span> <br>
                                            <span class="dadad">Date:</span>  {{ order.created }}
                                            <br>
                                        </div>
                                    {% endfor %}
                                </p>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <h4 class="notorders">You haven't ordered anything yet.</h4>
                {% endif %}         
            </div>
        </div>
{% endblock content %}

raredepot/users/templates/users/registration.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Registration{% endblock title %}

{% block content %}
    <section class="login-reg d-flex">
        <div class="login-title">
            <h2>Registration</h2>
            <form action="{% url "user:registration" %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="id_first_name" class="form-label form-stylereg">First Name</label>
                        <input type="text" class="form-control form-stylereg" id="id_first_name"
                        value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                        name="first_name" placeholder="Your First Name" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_last_name" class="form-label form-stylereg">Last Name</label>
                        <input type="text" class="form-control form-stylereg" id="id_last_name"
                        value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                        name="last_name" placeholder="Your Last Name" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_username" class="form-label form-stylereg">Username</label>
                        <input type="text" class="form-control form-stylereg" id="id_username"
                        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                        name="username" placeholder="Your Username" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_email" class="form-label form-stylereg">Email</label>
                        <input type="email" class="form-control form-stylereg" id="id_email"
                        value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                        name="email" placeholder="Your Email" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_password1" class="form-label form-stylereg">Password</label>
                        <input type="password" class="form-control form-stylereg" id="id_password1"
                        value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                        name="password1" placeholder="Your Password" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_password2" class="form-label form-stylereg">Confirm Password</label>
                        <input type="password" class="form-control form-stylereg" id="id_password2"
                        value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                        name="password2" placeholder="Your Password" required>
                    </div>
                </div>
                <button type="submit" class="login-btn form-style">Register</button>
            </form>
        </div>
    </section>
{% endblock content %}